KEYBOARD_TYPES_CONTACT = 'contact'
KEYBOARD_TYPES_REPORT = 'report'
KEYBOARD_TYPES_YES_NO = 'yes_no'
GET_REPORT_TEXT = 'Получить отчёт по дислокации вагонов'

HEADER_FORMAT = {'align': 'left',
                 'valign': 'top',
                 'border': 1,
                 'text_wrap': 1,
                 'font_name': 'Arial',
                 'font_size': 10,
                 'bold': 1,
                 'bg_color': '#ebebcc',
                 'font_color': '#64512d',
                 'top_color': '#a0a0a0',
                 'bottom_color': '#a0a0a0',
                 'left_color': '#a0a0a0',
                 'right_color': '#a0a0a0'}
PARTNER_FORMAT = {'align': 'left',
                  'valign': 'top',
                  'border': 1,
                  'text_wrap': 1,
                  'font_name': 'Arial',
                  'font_size': 10,
                  'bold': 1,
                  'bg_color': '#f2f1d9',
                  'font_color': '#64512d',
                  'top_color': '#a0a0a0',
                  'bottom_color': '#a0a0a0',
                  'left_color': '#a0a0a0',
                  'right_color': '#a0a0a0'}
FEATURE_FORMAT = {'align': 'left',
                  'valign': 'top',
                  'border': 1,
                  'text_wrap': 1,
                  'font_name': 'Arial',
                  'font_size': 8,
                  'bold': 1,
                  'bg_color': '#fffbf0',
                  'font_color': '#64512d',
                  'top_color': '#a0a0a0',
                  'bottom_color': '#a0a0a0',
                  'left_color': '#a0a0a0',
                  'right_color': '#a0a0a0'}
WAGON_FORMAT = {'align': 'left',
                'valign': 'top',
                'border': 1,
                'text_wrap': 1,
                'font_name': 'Arial',
                'font_size': 8,
                'bold': 1,
                'top_color': '#a0a0a0',
                'bottom_color': '#a0a0a0',
                'left_color': '#a0a0a0',
                'right_color': '#a0a0a0'}
MAIN_TEXT_FORMAT = {'align': 'left',
                    'valign': 'top',
                    'border': 1,
                    'text_wrap': 1,
                    'font_name': 'Arial',
                    'font_size': 8,
                    'top_color': '#a0a0a0',
                    'bottom_color': '#a0a0a0',
                    'left_color': '#a0a0a0',
                    'right_color': '#a0a0a0'}
MAIN_DIGIT_0_FORMAT = {'align': 'right',
                       'valign': 'top',
                       'border': 1,
                       'text_wrap': 1,
                       'font_name': 'Arial',
                       'font_size': 8,
                       'num_format': '# ###',
                       'top_color': '#a0a0a0',
                       'bottom_color': '#a0a0a0',
                       'left_color': '#a0a0a0',
                       'right_color': '#a0a0a0'}
MAIN_DIGIT_1_FORMAT = {'align': 'right',
                       'valign': 'top',
                       'border': 1,
                       'text_wrap': 1,
                       'font_name': 'Arial',
                       'font_size': 8,
                       'num_format': '# ##0.0',
                       'top_color': '#a0a0a0',
                       'bottom_color': '#a0a0a0',
                       'left_color': '#a0a0a0',
                       'right_color': '#a0a0a0'}
MAIN_DIGIT_2_FORMAT = {'align': 'right',
                       'valign': 'top',
                       'border': 1,
                       'text_wrap': 1,
                       'font_name': 'Arial',
                       'font_size': 8,
                       'num_format': '# ##0.00',
                       'top_color': '#a0a0a0',
                       'bottom_color': '#a0a0a0',
                       'left_color': '#a0a0a0',
                       'right_color': '#a0a0a0'}
